name: generating_pdf_reports

on: push

jobs:
  pdf_report:
    runs-on: ubuntu-22.04
    env:
      MPLBACKEND: Agg
    steps:
      - uses: actions/checkout@v4

      - name: Create requirements.txt for caching
        run: |
          cat > requirements.txt <<'EOF'
          nbconvert[webpdf]
          jupyter
          numpy
          scipy
          pandas
          matplotlib
          pint
          open-atmos-jupyter-utils
          PyMPDATA
          EOF

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13.2'
          cache: 'pip'
          cache-dependency-path: 'requirements.txt'

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true   # niech brak PyMPDATA nie przerwie joba

      - name: Execute notebook & export to PDF (webpdf)
        run: |
          jupyter nbconvert \
            --to webpdf \
            --allow-chromium-download \
            --execute "Projekt_MUP2.ipynb" \
            --ExecutePreprocessor.timeout=1800 \
            --output "Projekt_MUP2.pdf"

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: Projekt_MUP2.ipynb
          path: Projekt_MUP2.pdf

